//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniIspit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZavrsniIspitEntities : DbContext
    {
        public ZavrsniIspitEntities()
            : base("name=ZavrsniIspitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DnevnaProizvodnjaMlijeka> DnevnaProizvodnjaMlijekas { get; set; }
        public virtual DbSet<Krava> Kravas { get; set; }
        public virtual DbSet<Pasmina> Pasminas { get; set; }
    }
}
