//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniIspit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DnevnaProizvodnjaMlijeka
    {
        public int IDDnevnaProizvodnjaMlijeka { get; set; }
        public int DnevnaKolicinaMlijekaLitre { get; set; }
        public double ProsjecniPostotakMasnoce { get; set; }
        public double ProsjecniPostotakMikroorganizama { get; set; }
        public System.DateTime DatumMuznje { get; set; }
        public int KravaID { get; set; }
    
        public virtual Krava Krava { get; set; }
    }
}
