//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniIspit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Krava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Krava()
        {
            this.DnevnaProizvodnjaMlijekas = new HashSet<DnevnaProizvodnjaMlijeka>();
        }
    
        public int IDKrava { get; set; }
        public string Ime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public System.DateTime DatumDolaskaNaFarmu { get; set; }
        public string JedinstveniVeterinarskiBroj { get; set; }
        public int BrojTeladi { get; set; }
        public int PasminaID { get; set; }
        public int SlikaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DnevnaProizvodnjaMlijeka> DnevnaProizvodnjaMlijekas { get; set; }
        public virtual Pasmina Pasmina { get; set; }
        public virtual Slika Slika { get; set; }
    }
}
