//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniIspit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slika()
        {
            this.Kravas = new HashSet<Krava>();
        }
    
        public int IDSlika { get; set; }
        public string Putanja { get; set; }
        public string NazivSlike { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Krava> Kravas { get; set; }
    }
}
